### ISSUE TITLE
Min and Max stream length bug

### ISSUE THREAD

**Issue by Bobby4256** [YTP-Plus/YTPPlusPlusPlus#5]
**Describe the bug**
When you type the minimum and maximum stream length, exit the application, re enter it, it will swap the two values.

**To Reproduce**
1. Go to 'YTP+++'
2. Click on 'Min stream length and type it in, then  max stream length and type it in'

**Expected behavior**
Minimum should not have the highest number

**Screenshots**
If applicable, add screenshots to help explain your problem. No. screenshots won't help here as it can be easily faked either way.

**Desktop:**
 - OS: WINDOWS 10
 - Version [3.05]

**Additional context**
No additional context needed. I hope I did this right.

**Comment by KiwifruitDev** [comment]
https://github.com/YTP-Plus/YTPPlusPlusPlus/commit/f49beae8d9ac4ea0f8a6ee5860243de35212ebc3 should fix this, mind updating to the latest version?
You can do so inside of YTP+++ by going to **Help** -> **Show Tutorial Window**.
If this solves the issue, let me know and I'll close it. :)

**Comment by Bobby4256** [comment]
Yeah sure! I'll edit this when I update and check it. Another thing I forgor to mention is that overlays are broken. They cause fatal errors. I have mentioned this before but it is still happening. I think it may be because of the aspect ratio or the clip is too long and it causes a error, both of which can be fixed (maybe I don't know python). 
Only fix it if needed, I don't want to put stress on you. 
Have a good day :)

**Comment by danylopez123** [comment]
For the current version 3.0.9 i have, the Min and Max Stream Duration doesn't seem to behave right, i put for example 0.15 as Min and 5 as Max and i see most of the clips going longer than the 5 seconds i put max.

**Comment by KiwifruitDev** [comment]
Try using v3.1.3 or higher from now on.

**Comment by danylopez123** [comment]
> 

The problem it's still present in v3.1.4, no matter what i put for Min and Max, this is still going random.

**Comment by KiwifruitDev** [comment]
> > 
> 
> The problem it's still present in v3.1.4, no matter what i put for Min and Max, this is still going random.

Some plugins will use their own length of time, the min/max stream duration is the range of how much time each clip is to work with
I'm currently working on the plugin browser so I'll be sure to change this in the future

**Comment by KiwifruitDev** [comment]
This software is no longer supported.

https://store.steampowered.com/app/2516360/Nonsensical_Video_Generator/
